#!/usr/bin/env bash

# check if the current dir is a git repo
if [ -d ".git" ]; then
    echo "The dir is a git repo..."
    echo "Initializing commitbuddy..."
    curl -o .git/hooks/commitbuddy https://raw.githubusercontent.com/VedantWankhade/commitbuddy/master/bin/commitbuddy
    curl -o .git/hooks/prepare-commit-msg https://raw.githubusercontent.com/VedantWankhade/commitbuddy/master/prepare-commit-msg
else
    echo "Current directory is not a Git directory."
fi